# SwiftLint Configuration for Kalendar
# https://github.com/realm/SwiftLint

# Include all Swift files
included:
  - Kalendar
  - KalendarTests
  - KalendarUITests
  - LockScreenCalendarWidget
  - WidgetExtension

# Exclude generated and third-party files
excluded:
  - .build
  - .git
  - .github
  - Pods
  - build
  - DerivedData
  - "*.generated.swift"

# Enabled rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - unused_private_declaration
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Disabled rules
disabled_rules:
  - todo # Allow TODO comments
  - line_length # We'll use a custom line length
  - type_body_length # Views can be long

# Custom rule configurations
line_length:
  warning: 120
  error: 150
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 800
  ignore_comment_only_lines: true

function_body_length:
  warning: 60
  error: 100

type_name:
  min_length: 3
  max_length: 40
  excluded: 
    - UI

identifier_name:
  min_length: 2
  max_length: 40
  excluded:
    - id
    - x
    - y
    - z
    - to
    - in
    - at
    - on
    - of
    - by
    - up
    - it

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 3
    error: 6
  statement_level:
    warning: 5
    error: 10

# Custom rules
custom_rules:
  # Force unwrapping should be avoided
  force_unwrapping_rule:
    name: "Force unwrapping"
    regex: '!\s*(?![\s\}])'
    message: "Avoid force unwrapping optionals"
    severity: warning

  # Print statements should not be committed
  no_print:
    name: "Print statements"
    regex: 'print\s*\('
    message: "Remove print statements before committing"
    severity: warning
    excluded: ".*Tests.*"

  # Mark comments should be properly formatted
  mark_comment:
    name: "MARK Comment"
    regex: '\/\/\s*MARK:\s*-[^-]'
    message: "MARK comments should have a space after the dash"
    severity: warning

  # No hardcoded strings in UI
  hardcoded_strings:
    name: "Hardcoded Strings"
    regex: 'Text\s*\(\s*"[^"]*"\s*\)'
    message: "Consider using localized strings"
    severity: warning
    excluded: ".*Tests.*"

# File header template
file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*\.swift
                    \/\/  .*
                    \/\/
                    \/\/  Created by .* on \d{2}\.\d{2}\.\d{2}\.
                    \/\/

# Reporter types
reporter: "xcode"

# Analyzer rules
analyzer_rules:
  - explicit_self
  - unused_import
  - unused_declaration
