name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  DEVELOPER_DIR: /Applications/Xcode_16.1.app/Contents/Developer

jobs:
  test:
    name: Test
    runs-on: macos-14
    strategy:
      matrix:
        scheme: [Kalendar]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.1'

      - name: Cache derived data
        uses: actions/cache@v4
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-derived-data-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-derived-data-

      - name: Cache SwiftPM (global)
        uses: actions/cache@v4
        with:
          path: ~/Library/Caches/org.swift.swiftpm
          key: ${{ runner.os }}-swiftpm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-swiftpm-

      - name: List Available Simulators
        run: |
          echo "Available simulators:"
          xcrun simctl list devices available | head -30
          echo ""
          echo "iPhone simulators:"
          xcrun simctl list devices available | grep "iPhone" || echo "No iPhone simulators found"

      - name: Test
        run: |
          echo "Building app and running unit tests only..."
          xcodebuild \
            -project Kalendar.xcodeproj \
            -scheme ${{ matrix.scheme }} \
            -configuration Debug \
            -destination "platform=iOS Simulator,name=iPhone 16" \
            build test \
            -only-testing:KalendarTests \
            -skip-testing:KalendarUITests \
            CODE_SIGNING_ALLOWED=NO \
            | xcpretty && exit ${PIPESTATUS[0]}

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-results-${{ matrix.scheme }}
          path: |
            ~/Library/Developer/Xcode/DerivedData/**/Logs/Test/*.xcresult

  widget-test:
    name: Widget Tests
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.1'

      - name: Test Widget Logic
        run: |
          echo "Building app and testing widget logic within KalendarTests..."
          xcodebuild \
            -project Kalendar.xcodeproj \
            -scheme Kalendar \
            -configuration Debug \
            -destination "platform=iOS Simulator,name=iPhone 16" \
            build test \
            -only-testing:KalendarTests/WidgetCalendarDayTests,KalendarTests/WidgetPerformanceTests \
            -skip-testing:KalendarUITests \
            CODE_SIGNING_ALLOWED=NO \
            | xcpretty && exit ${PIPESTATUS[0]}

  lint:
    name: Lint
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.1'

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        run: swiftlint lint --reporter github-actions-logging

      - name: Analyze Code
        run: |
          xcodebuild \
            -project Kalendar.xcodeproj \
            -scheme Kalendar \
            -configuration Debug \
            analyze \
            CODE_SIGNING_ALLOWED=NO \
            | xcpretty && exit ${PIPESTATUS[0]}

  security:
    name: Security Scan
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run security scan
        run: |
          if grep -r "password\|secret\|key\|token" --include="*.swift" --include="*.m" --include="*.h" . | grep -v "// Test" | grep -v "placeholder"; then
            echo "❌ Potential hardcoded secrets found"
            exit 1
          else
            echo "✅ No hardcoded secrets found"
          fi

      - name: Check Info.plist files
        run: |
          find . -name "Info.plist" -exec plutil -lint {} \;

  coverage:
    name: Code Coverage
    runs-on: macos-14
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.1'

      - name: Test with Coverage
        run: |
          xcodebuild \
            -project Kalendar.xcodeproj \
            -scheme Kalendar \
            -destination "platform=iOS Simulator,name=iPhone 16" \
            -configuration Debug \
            build test \
            -only-testing:KalendarTests \
            -enableCodeCoverage YES \
            CODE_SIGNING_ALLOWED=NO \
            | xcpretty && exit ${PIPESTATUS[0]}

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ~/Library/Developer/Xcode/DerivedData/**/Logs/Test/*.xcresult
          fail_ci_if_error: false

  performance:
    name: Performance Tests
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.1'

      - name: Run Performance Tests
        run: |
          xcodebuild \
            -project Kalendar.xcodeproj \
            -scheme Kalendar \
            -destination "platform=iOS Simulator,name=iPhone 16" \
            -configuration Release \
            build test \
            -only-testing:KalendarTests/testCalendarGenerationPerformance \
            -skip-testing:KalendarUITests \
            CODE_SIGNING_ALLOWED=NO \
            | xcpretty && exit ${PIPESTATUS[0]}

      - name: Upload Performance Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: performance-results
          path: |
            ~/Library/Developer/Xcode/DerivedData/**/Logs/Test/*.xcresult

  build-release:
    name: Build Release
    runs-on: macos-14
    if: github.ref == 'refs/heads/main'
    needs: [test, widget-test, lint, security]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.1'

      - name: Build Release (archive)
        run: |
          xcodebuild \
            -project Kalendar.xcodeproj \
            -scheme Kalendar \
            -configuration Release \
            -archivePath ./build/Kalendar.xcarchive \
            archive \
            CODE_SIGNING_ALLOWED=NO \
            | xcpretty && exit ${PIPESTATUS[0]}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-build
          path: ./build/
